In [2]:
import matplotlib.pyplot as plt
import numpy as np

#### *Let us understand Maths by implementing, In your data science journey you cannot get the complete interpretation of the algorithms without knowing the underlying math.*

Don't change the below code

In [3]:
# Line: x + y = 6  →  y = 6 - x
x = np.linspace(0, 7, 100)
y = 6 - x

# Points
left_points = [(1,1), (2,1)]
right_points = [(5,4), (4,3)]
on_line =[(3,3),(2,4)]
q=(1,6)

plt.plot(x, y)

for p in left_points:
    plt.scatter(p[0], p[1])
    plt.text(p[0]+0.1, p[1], f"{p[0],p[1]}")

for p in right_points:
    plt.scatter(p[0], p[1])
    plt.text(p[0]+0.1, p[1], f"{p[0],p[1]}")

for p in on_line:
    plt.scatter(p[0], p[1])
    plt.text(p[0]+0.1, p[1], f"{p[0],p[1]}")

plt.scatter(q[0],q[1])
plt.text(q[0]+0.1, q[1], f"{q[0],q[1]}-->q")

plt.axhline(0)
plt.axvline(0)
plt.grid(True)
plt.title("Point Position Using x + y - 6 = 0")
plt.xlabel("X")
plt.ylabel("Y")
plt.show()


1. In the above graph we can see some points to the right of the line, left of the line and also on the line.
2. we can also see a point q.
3. let us try to do some math on these points.



#### Task–1:

1. Calculate the **Euclidean distance** between the query point \(q\) and **all the points on the left side** of the line.

2. Calculate the **Euclidean distance** between the query point \(q\) and **all the points on the right side** of the line.

3. Similarly, calculate the **Euclidean distance** between the query point \(q\) and **a point lying on the line**.

4. Based on your calculations, answer the following:
   - Which point is **nearest to the query point \(q\)?**

---


In [ ]:
# code here

###### 1.Calculate the Euclidean distance between the query point (q) and all the points on the left side of the line.

In [ ]:
left_points = [(1,1), (2,1)]
q=(1,6)

In [5]:
from sklearn.metrics.pairwise import euclidean_distances

In [6]:
euclidean_distances(left_points,[q])

array([[5.        ],
       [5.09901951]])

###### 2.Calculate the Euclidean distance between the query point (q) and all the points on the right side of the line.

In [ ]:
right_points = [(5,4), (4,3)]
q=(1,6)

In [7]:
euclidean_distances(right_points,[q])

array([[4.47213595],
       [4.24264069]])

###### 3.Similarly, calculate the Euclidean distance between the query point (q) and a point lying on the line.

In [ ]:
on_line =[(3,3),(2,4)]

In [8]:
euclidean_distances(on_line,[q])

array([[3.60555128],
       [2.23606798]])

###### Which point is nearest to the query point (q)?

In [ ]:
(2,4) -->online point is nearest to q

#### Task -2


In [9]:
line_exp = lambda x, y: 1*x + 1*y - 6 # the equation is x+y-6=0
line_exp(0,0) # substitute the x and y values

-6

1. What do you notice about the sign of the values for:

*   Left-side points?
*   Right-side points?
*   The point on the line?

2. Where does the query point q lie based on its output?

3. What general rule can you infer about the expression 1*x + 1*y - 6?

4. If i give another point w that is not present can you identify on which side of the plane will the point reside?



In [ ]:
# code here

###### 1.What do you notice about the sign of the values for:


In [ ]:
Left-side points?
left_points = [(1,1), (2,1)]

In [10]:
print(line_exp(1,1),line_exp(2,1))## negative sign for leftside point

-4 -3


In [ ]:
Right-side points?
right_points = [(5,4), (4,3)]

In [11]:
print(line_exp(5,4),line_exp(4,3))## positive sign for rightside points to line

3 1


In [ ]:
The point on the line?
on_line =[(3,3),(2,4)]

In [12]:
print(line_exp(3,3),line_exp(2,4))

0 0


###### 2.Where does the query point q lie based on its output?

In [14]:
print(line_exp(1,6))## positive sign so q point lies rightside of line

1


###### 3.What general rule can you infer about the expression 1x + 1y - 6?

In [ ]:
## negative sign for leftside point
## positive sign for rightside points to line
## zero sign on the line

###### 4.If i give another point w that is not present can you identify on which side of the plane will the point reside?

In [19]:
print(line_exp(4,7)),print(line_exp(2,2))#point1-->rightside,##point2-->leftside

5
-2


(None, None)

### Task3: Classify Points Using the Dot Product with Normal

We have the line:

\[
x + y - 6 = 0
\]

1. The vector perpendicular to the line is called the **normal**, and it is:
\[
n = (1, 1)
\]

2. You are given the following points:

- Left-side candidates: P1 = (1,1), P2 = (2,1)  
- Right-side candidates: P3 = (5,4), P4 = (4,3)  
- On the line: P5 = (3,3), P6 = (2,4)  
- Query point: q = (2,4)

---

#### Instructions:

1. For each point \(p = (x, y)\), compute the expression:
\(
n \.p - 6
\)

2. Based on the **sign of `value`**, classify the point as:

- **Right of the line** (value > 0)  
- **Left of the line** (value < 0)  
- **On the line** (value = 0)

3. Document your results in a dataframe showing:

| Point | Value | Classification |
|-------|-------|----------------|

4. Do the same for the query point `q`.


In [37]:
n= np.array([1,1]) # this is the normal vector of the equation x+y-6=0
p=np.array([2,4])
int(np.dot(n,p)-6) #----> here the point is (2,4) when computed dot product with (1,1) i.e. normal and subtract 6, the result is 0.
# this point lies on the line.

0

In [ ]:
# code here

In [25]:
left_points = [(1,1), (2,1)]
right_points = [(5,4), (4,3)]
on_line =[(3,3),(2,4)]
q=(2,4)

In [26]:
col=[left_points,right_points,on_line,q]

In [27]:
d={}
l=[]

In [40]:
import numpy as np

left_points = [(1,1), (2,1)]
right_points = [(5,4), (4,3)]
on_line = [(3,3), (2,4)]
q = (2,4)

col = [left_points, right_points, on_line, q]

n = np.array([1, 1])  # normal vector
l = []                # to store results

for item in col:
    # item can be a list of points OR a single point
    if isinstance(item, tuple):      # single point like (2,4)
        points = [item]
    else:                            # list of points like [(1,1),(2,1)]
        points = item

    for x, y in points:
        p = np.array([x, y])
        d = np.dot(n, p) - 6   # x + y - 6

        if d > 0:
            side = 'rightside'
        elif d < 0:
            side = 'leftside'
        else:
            side = 'on_line'

        l.append([(x, y), d, side])

print(l)


[[(1, 1), np.int64(-4), 'leftside'], [(2, 1), np.int64(-3), 'leftside'], [(5, 4), np.int64(3), 'rightside'], [(4, 3), np.int64(1), 'rightside'], [(3, 3), np.int64(0), 'on_line'], [(2, 4), np.int64(0), 'on_line'], [(2, 4), np.int64(0), 'on_line']]


In [42]:
import pandas as pd

In [43]:
pd.DataFrame(l,columns=['point','value','classification'])

point  value classification
0  (1, 1)     -4       leftside
1  (2, 1)     -3       leftside
2  (5, 4)      3      rightside
3  (4, 3)      1      rightside
4  (3, 3)      0        on_line
5  (2, 4)      0        on_line
6  (2, 4)      0        on_line

### Task 4: Classify Points and Compute Distances for Planes.

#### 1: Calculate the euclidean distance between these 2 points {p1=(10,1,2), p2=(11,10,2)}

#### 2: 3D Plane
- Plane: x + y + z - 6 = 0
- Points: A(1,1,1), B(2,2,2), C(3,2,2), q(2,1,3)
- Compute:
  1. Dot product: n · p - d
  2. Side of the plane (Above/Below/On)
- Document results in a table:

| Point | Value | Classification |
|-------|-------|----------------|

###### 1.Calculate the euclidean distance between these 2 points {p1=(10,1,2), p2=(11,10,2)}

In [53]:
p1=np.array([[10,1,2]])
p2=np.array([[11,10,2]])
p1,p2

(array([[10,  1,  2]]), array([[11, 10,  2]]))

In [54]:
euclidean_distances(p1,p2)

array([[9.05538514]])

###### 3d_plane

In [ ]:
Plane: x + y + z - 6 = 0
Points: A(1,1,1), B(2,2,2), C(3,2,2), q(2,1,3)

In [72]:
import numpy as np

a=(1,1,1)
b=(2,2,2)
c=(3,2,2)
q=(2,1,3)

col = [a, b,c, q]

n = np.array([1,1,1])  # normal vector
l = []                # to store results

for item in col:
        p = np.array(item)
        print(p)
        d = np.dot(n, p) - 6   # x + y - 6

        if d > 0:
            side = 'rightside'
        elif d < 0:
            side = 'leftside'
        else:
            side = 'on_line'

        l.append([p, d, side])

print(l)


[1 1 1]
[2 2 2]
[3 2 2]
[2 1 3]
[[array([1, 1, 1]), np.int64(-3), 'leftside'], [array([2, 2, 2]), np.int64(0), 'on_line'], [array([3, 2, 2]), np.int64(1), 'rightside'], [array([2, 1, 3]), np.int64(0), 'on_line']]


In [73]:
pd.DataFrame(l,columns=['point','value','classification'])

point  value classification
0  [1, 1, 1]     -3       leftside
1  [2, 2, 2]      0        on_line
2  [3, 2, 2]      1      rightside
3  [2, 1, 3]      0        on_line

### Task 5: Classify Points and Compute Distances for Hyperplanes

#### 1: Calculate the euclidean distance between these 2 points {p1=(10,1,2,3), p2=(11,10,2,5)}

#### 2: 4D Hyperplane
- Hyperplane: 2x1 + x2 - x3 + x4 - 5 = 0
- Points: P1(1,1,0,2), P2(2,0,1,1), P3(1,2,1,1), q(1,1,1,1)
- Compute:
  1. Dot product: n · p + b , where n is the normal vector and p is the data point b is the intercept.
  2. Euclidean distance from hyperplane
  3. Side (Positive/Negative/On)
- Document results in a table:

| Point | Value | Classification |
|-------|-------|----------------|


In [74]:
a=(1,1,0,2)
b=(2,0,1,1)
c=(1,2,1,1)
q=(1,1,1,1)

col = [a, b,c, q]

n = np.array([2,1,-1,1])  # normal vector
l = []                # to store results

for item in col:
        p = np.array(item)
        print(p)
        d = np.dot(n, p) - 6   # x + y - 6

        if d > 0:
            side = 'rightside'
        elif d < 0:
         side = 'leftside'
        else:
            side = 'on_line'

        l.append([p, d, side])

print(l)


[1 1 0 2]
[2 0 1 1]
[1 2 1 1]
[1 1 1 1]
[[array([1, 1, 0, 2]), np.int64(-1), 'leftside'], [array([2, 0, 1, 1]), np.int64(-2), 'leftside'], [array([1, 2, 1, 1]), np.int64(-2), 'leftside'], [array([1, 1, 1, 1]), np.int64(-3), 'leftside']]


In [75]:
pd.DataFrame(l,columns=['point','value','classification'])

point  value classification
0  [1, 1, 0, 2]     -1       leftside
1  [2, 0, 1, 1]     -2       leftside
2  [1, 2, 1, 1]     -2       leftside
3  [1, 1, 1, 1]     -3       leftside